//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_VR_Input_actions : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean TriggerClick
        {
            get
            {
                return SteamVR_Actions.vR_Input_actions_TriggerClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchpadClick
        {
            get
            {
                return SteamVR_Actions.vR_Input_actions_TouchpadClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean Touchpadtouch
        {
            get
            {
                return SteamVR_Actions.vR_Input_actions_Touchpadtouch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Touchpadpos
        {
            get
            {
                return SteamVR_Actions.vR_Input_actions_Touchpadpos;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuButton
        {
            get
            {
                return SteamVR_Actions.vR_Input_actions_MenuButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean SystemButton
        {
            get
            {
                return SteamVR_Actions.vR_Input_actions_SystemButton;
            }
        }
        
        public virtual SteamVR_Action_Single TriggerSqueeze
        {
            get
            {
                return SteamVR_Actions.vR_Input_actions_TriggerSqueeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean Forward
        {
            get
            {
                return SteamVR_Actions.vR_Input_actions_Forward;
            }
        }
        
        public virtual SteamVR_Action_Boolean Backward
        {
            get
            {
                return SteamVR_Actions.vR_Input_actions_Backward;
            }
        }
        
        public virtual SteamVR_Action_Boolean Center
        {
            get
            {
                return SteamVR_Actions.vR_Input_actions_Center;
            }
        }
        
        public virtual SteamVR_Action_Boolean Left
        {
            get
            {
                return SteamVR_Actions.vR_Input_actions_Left;
            }
        }
        
        public virtual SteamVR_Action_Boolean Right
        {
            get
            {
                return SteamVR_Actions.vR_Input_actions_Right;
            }
        }
        
        public virtual SteamVR_Action_Boolean DoubleGrab
        {
            get
            {
                return SteamVR_Actions.vR_Input_actions_DoubleGrab;
            }
        }
        
        public virtual SteamVR_Action_Boolean LongGrip
        {
            get
            {
                return SteamVR_Actions.vR_Input_actions_LongGrip;
            }
        }
    }
}
